import { QuizItem } from "../types";

export const LV1_SECURITIES_CHOICE: QuizItem[] = [
  {
    id: "lv1-securities-1",
    level: "lv-1",
    topic: "증권사 선택",
    topicIndex: 7,
    type: "OX",
    question: "증권사마다 주식 매매 수수료가 동일하다.",
    answer: "X",
    explanation: "증권사마다 수수료율과 혜택이 다르므로 비교 후 선택해야 한다.",
  },
  {
    id: "lv1-securities-2",
    level: "lv-1",
    topic: "증권사 선택",
    topicIndex: 7,
    type: "OX",
    question: "모바일 주식거래를 자주 한다면 MTS 사용이 편리한 증권사를 고르는 것이 좋다.",
    answer: "O",
    explanation:
      "MTS 기능과 편의성은 증권사마다 차이가 크므로, 모바일 거래 중심이라면 중요한 요소다.",
  },
  {
    id: "lv1-securities-3",
    level: "lv-1",
    topic: "증권사 선택",
    topicIndex: 8,
    type: "MULTI",
    question: "증권사를 선택할 때 고려할 요소가 아닌 것은?",
    options: ["수수료율", "거래 프로그램 편의성", "거래소의 개장 시간"],
    answer: "거래소의 개장 시간",
    explanation: "개장 시간은 증권사와 관계없이 동일하다.",
  },
  {
    id: "lv1-securities-4",
    level: "lv-1",
    topic: "증권사 선택",
    topicIndex: 7,
    type: "MULTI",
    question: "해외 주식 거래를 주로 한다면 무엇을 우선 확인해야 할까?",
    options: ["해외 시장 지원 여부", "거래소 위치", "주식 종목 수"],
    answer: "해외 시장 지원 여부",
    explanation: "일부 증권사는 특정 국가의 주식 거래를 지원하지 않는다.",
  },
  {
    id: "lv1-securities-5",
    level: "lv-1",
    topic: "증권사 선택",
    topicIndex: 7,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["종합증권사", "특화증권사", "온라인증권사"],
    rightItems: [
      "주식, 채권, 펀드 등 다양한 금융상품을 제공하는 증권사",
      "특정 분야에 강점을 가진 증권사",
      "주로 비대면, 모바일 중심으로 거래하는 증권사",
    ],
    answer: {
      종합증권사: "주식, 채권, 펀드 등 다양한 금융상품을 제공하는 증권사",
      특화증권사: "특정 분야에 강점을 가진 증권사",
      온라인증권사: "주로 비대면, 모바일 중심으로 거래하는 증권사",
    },
    explanation: "증권사마다 제공 서비스와 강점이 다르다.",
  },
  {
    id: "lv1-securities-6",
    level: "lv-1",
    topic: "증권사 선택",
    topicIndex: 7,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["리서치 보고서", "해외 주식 지원", "고객센터"],
    rightItems: [
      "증권사에서 제공하는 종목 분석 자료",
      "외국 거래소의 주식을 매매할 수 있는 서비스",
      "문의나 문제 해결을 지원하는 부서",
    ],
    answer: {
      리서치보고서: "증권사에서 제공하는 종목 분석 자료",
      해외주식지원: "외국 거래소의 주식을 매매할 수 있는 서비스",
      고객센터: "문의나 문제 해결을 지원하는 부서",
    },
    explanation: "부가 서비스 역시 증권사 선택의 중요한 요소다.",
  },
];
