import { QuizItem } from "../types";

export const LV1_ACCOUNT_OPENING: QuizItem[] = [
  {
    id: "lv1-account-opening-1",
    level: "lv-1",
    topic: "주식계좌 개설",
    topicIndex: 8,
    type: "OX",
    question: "주식계좌는 은행 창구에서도 개설할 수 있다.",
    answer: "O",
    explanation: "은행과 증권사가 제휴되어 있는 경우 창구에서 계좌 개설이 가능하다.",
  },
  {
    id: "lv1-account-opening-2",
    level: "lv-1",
    topic: "주식계좌 개설",
    topicIndex: 8,
    type: "OX",
    question: "주식 거래를 위해서는 은행계좌만 있으면 된다.",
    answer: "X",
    explanation: "주식 매수·매도는 반드시 ‘증권계좌’가 있어야 가능하다.",
  },
  {
    id: "lv1-account-opening-3",
    level: "lv-1",
    topic: "주식계좌 개설",
    topicIndex: 8,
    type: "MULTI",
    question: "주식계좌 개설 방법이 아닌 것은?",
    options: ["비대면 개설", "증권사 방문 개설", "우편으로 신청 후 개설"],
    answer: "우편으로 신청 후 개설",
    explanation: "현재 주식계좌는 우편 신청 방식으로 개설할 수 없다.",
  },
  {
    id: "lv1-account-opening-4",
    level: "lv-1",
    topic: "주식계좌 개설",
    topicIndex: 8,
    type: "MULTI",
    question: "비대면 계좌 개설 시 필수로 필요한 것은?",
    options: ["신분증과 본인 명의 휴대폰", "주민등록등본", "인감도장"],
    answer: "신분증과 본인 명의 휴대폰",
    explanation: "본인 인증을 위해 신분증과 본인 명의 휴대폰이 필수다.",
  },
  {
    id: "lv1-account-opening-5",
    level: "lv-1",
    topic: "주식계좌 개설",
    topicIndex: 8,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["은행 방문", "증권사 지점 방문", "비대면 개설"],
    rightItems: [
      "제휴 증권사의 계좌를 은행 창구에서 개설",
      "직접 증권사 영업점을 찾아 계좌 개설",
      "모바일 앱으로 24시간 계좌 개설",
    ],
    answer: {
      은행방문: "제휴 증권사의 계좌를 은행 창구에서 개설",
      증권사지점방문: "직접 증권사 영업점을 찾아 계좌 개설",
      비대면개설: "모바일 앱으로 24시간 계좌 개설",
    },
    explanation: "계좌 개설 방식마다 절차와 편의성이 다르다.",
  },
  {
    id: "lv1-account-opening-6",
    level: "lv-1",
    topic: "주식계좌 개설",
    topicIndex: 8,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["은행 방문", "증권사 지점 방문", "비대면 개설"],
    rightItems: [
      "은행 영업시간 내 가능, 직원 안내 제공",
      "전문 상담과 다양한 상품 안내 가능",
      "장소와 시간 제약 없이 앱으로 진행",
    ],
    answer: {
      은행방문: "은행 영업시간 내 가능, 직원 안내 제공",
      증권사지점방문: "전문 상담과 다양한 상품 안내 가능",
      비대면개설: "장소와 시간 제약 없이 앱으로 진행",
    },
    explanation: "개설 방법별로 장단점이 다르므로 목적에 맞게 선택해야 한다.",
  },
];
