import { QuizItem } from "../types";

export const LV3_UNDERVALUE_STOCK: QuizItem[] = [
  {
    id: "lv3-undervalue-1",
    level: "lv-3",
    topic: "저평가 주식 찾기",
    topicIndex: 4,
    type: "OX",
    question: "저평가 주식이란 기업의 내재가치보다 시장 가격이 낮은 주식을 의미한다.",
    answer: "O",
    explanation: "기업 가치 대비 가격이 낮으면 ‘저평가’라 부르며, 투자 기회가 될 수 있다.",
  },
  {
    id: "lv3-undervalue-2",
    level: "lv-3",
    topic: "저평가 주식 찾기",
    topicIndex: 4,
    type: "MULTI",
    question: "저평가 여부를 판단할 때 활용하는 주요 지표가 아닌 것은?",
    options: ["PER", "PBR", "원/달러 환율"],
    answer: "원/달러 환율",
    explanation: "환율도 영향을 줄 수 있지만 직접적인 평가 지표는 아니에요.",
  },
  {
    id: "lv3-undervalue-3",
    level: "lv-3",
    topic: "저평가 주식 찾기",
    topicIndex: 4,
    type: "OX",
    question: "저평가 주식 투자에서 ‘안전마진’이란 손실 가능성을 줄일 수 있는 가격 여유를 말한다.",
    answer: "O",
    explanation: "안전마진은 가치보다 싼 가격에 매수해 위험을 줄이는 개념이에요.",
  },
  {
    id: "lv3-undervalue-4",
    level: "lv-3",
    topic: "저평가 주식 찾기",
    topicIndex: 4,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["PER", "PBR", "ROE"],
    rightItems: [
      "주가를 주당순이익으로 나눈 값",
      "주가를 주당순자산가치로 나눈 값",
      "자기자본 대비 순이익 비율",
    ],
    answer: {
      PER: "주가를 주당순이익으로 나눈 값",
      PBR: "주가를 주당순자산가치로 나눈 값",
      ROE: "자기자본 대비 순이익 비율",
    },
    explanation: "주요 지표를 알아야 기업의 저평가 여부를 판단할 수 있어요.",
  },
  {
    id: "lv3-undervalue-5",
    level: "lv-3",
    topic: "저평가 주식 찾기",
    topicIndex: 4,
    type: "MULTI",
    question: "저평가 판단에서 흔히 저지르는 실수가 아닌 것은?",
    options: [
      "단일 지표만 보고 투자",
      "업종 평균과 비교하지 않음",
      "여러 지표와 업황을 함께 고려",
    ],
    answer: "여러 지표와 업황을 함께 고려",
    explanation: "여러 지표와 업황을 함께 고려하는 것은 바람직한 투자 판단이에요.",
  },
  {
    id: "lv3-undervalue-6",
    level: "lv-3",
    topic: "저평가 주식 찾기",
    topicIndex: 4,
    type: "OX",
    question: "저평가 주식은 반드시 시간이 지나면 가치가 반영되어 주가가 오른다.",
    answer: "X",
    explanation: "기업이 성장하지 못하거나 시장이 외면하면 저평가 상태가 장기 지속될 수 있어요.",
  },
];
