import { QuizItem } from "../types";

export const LV2_DIVERSIFICATION: QuizItem[] = [
  {
    id: "lv2-div-1",
    level: "lv-2",
    topic: "분산투자",
    topicIndex: 0,
    type: "OX",
    question: "분산투자는 한 종목에만 투자하는 것을 말한다.",
    answer: "X",
    explanation: "분산투자는 여러 종목에 나눠 투자해 위험을 줄이는 방법이에요.",
  },
  {
    id: "lv2-div-2",
    level: "lv-2",
    topic: "분산투자",
    topicIndex: 0,
    type: "MULTI",
    question: "분산투자가 필요한 이유로 가장 적절한 것은 무엇일까?",
    options: [
      "수익률을 보장하기 위해서",
      "한 종목이 망해도 다른 종목이 손실을 줄여주기 때문에",
      "세금을 줄이기 위해서",
    ],
    answer: "한 종목이 망해도 다른 종목이 손실을 줄여주기 때문에",
    explanation: "분산투자는 위험을 분산시켜 큰 손실을 막아주는 안전장치예요.",
  },
  {
    id: "lv2-div-3",
    level: "lv-2",
    topic: "분산투자",
    topicIndex: 0,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["산업 분산", "지역 분산", "자산 분산"],
    rightItems: ["여러 산업에 투자", "다양한 나라와 지역에 투자", "주식, 채권, 현금 등을 나눠 투자"],
    answer: {
      "산업 분산": "여러 산업에 투자",
      "지역 분산": "다양한 나라와 지역에 투자",
      "자산 분산": "주식, 채권, 현금 등을 나눠 투자",
    },
    explanation: "분산투자는 산업, 지역, 자산을 다양하게 나누어 하는 게 핵심이에요.",
  },
  {
    id: "lv2-div-4",
    level: "lv-2",
    topic: "분산투자",
    topicIndex: 0,
    type: "OX",
    question: "분산투자를 하면 손실 위험을 완전히 없앨 수 있다.",
    answer: "X",
    explanation: "분산투자는 위험을 줄여주지만 손실 가능성을 완전히 없애지는 못해요.",
  },
  {
    id: "lv2-div-5",
    level: "lv-2",
    topic: "분산투자",
    topicIndex: 0,
    type: "MULTI",
    question: "분산투자를 실천하는 올바른 방법은 무엇일까?",
    options: [
      "한 산업의 여러 기업에만 투자한다",
      "산업과 지역을 다양하게 선택하고 주식·채권·현금까지 나눠 담는다",
      "단기 수익을 위해 한 종목에 집중한다",
    ],
    answer: "산업과 지역을 다양하게 선택하고 주식·채권·현금까지 나눠 담는다",
    explanation: "산업·지역·자산을 고르게 분산하는 것이 진짜 분산투자예요.",
  },
  {
    id: "lv2-div-6",
    level: "lv-2",
    topic: "분산투자",
    topicIndex: 0,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["위험 관리", "꾸준함", "안전장치"],
    rightItems: ["손실 가능성을 줄이는 것", "일정하게 계속 분산투자를 이어가는 것", "큰 손실을 막는 역할"],
    answer: {
      "위험 관리": "손실 가능성을 줄이는 것",
      꾸준함: "일정하게 계속 분산투자를 이어가는 것",
      안전장치: "큰 손실을 막는 역할",
    },
    explanation: "분산투자는 꾸준히 다양한 종목에 투자해 위험을 관리하는 안전장치예요.",
  },
];
