import { QuizItem } from "../types";

export const LV2_LEVERAGE: QuizItem[] = [
  {
    id: "lv2-lev-1",
    level: "lv-2",
    topic: "대출 투자",
    topicIndex: 1,
    type: "OX",
    question: "레버리지는 남의 돈(대출)으로 투자해 내 돈보다 큰 수익을 노리는 것을 말한다.",
    answer: "O",
    explanation: "빚을 이용해 투자 규모를 키우는 걸 레버리지라고 해요. 수익도 커지지만 위험도 함께 커져요.",
  },
  {
    id: "lv2-lev-2",
    level: "lv-2",
    topic: "대출 투자",
    topicIndex: 1,
    type: "MULTI",
    question:
      "2배 레버리지로 A자산에 투자했는데 기초자산이 +10% 상승했다. 수익률은 얼마일까? (비용 제외)",
    options: ["+10%", "+20%", "0%"],
    answer: "+20%",
    explanation: "레버리지는 노출을 2배로 키우므로 기초자산 변동의 약 2배로 움직여요.",
  },
  {
    id: "lv2-lev-3",
    level: "lv-2",
    topic: "대출 투자",
    topicIndex: 1,
    type: "OX",
    question: "2배 레버리지 상태에서 기초자산이 -10% 하락하면 내 손실은 약 -20%가 된다.",
    answer: "O",
    explanation: "수익이 두 배로 커지는 만큼 손실도 두 배로 커져요. 하락장에서 빠르게 손실이 커질 수 있어요.",
  },
  {
    id: "lv2-lev-4",
    level: "lv-2",
    topic: "대출 투자",
    topicIndex: 1,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["레버리지", "이자비용", "마진콜"],
    rightItems: [
      "대출 등을 활용해 투자 규모를 키우는 것",
      "빚을 쓴 대가로 내야 하는 비용",
      "담보가 부족해 추가 증거금을 요구받거나 강제 청산될 수 있는 상황",
    ],
    answer: {
      레버리지: "대출 등을 활용해 투자 규모를 키우는 것",
      이자비용: "빚을 쓴 대가로 내야 하는 비용",
      마진콜: "담보가 부족해 추가 증거금을 요구받거나 강제 청산될 수 있는 상황",
    },
    explanation: "레버리지의 장단을 이해하려면 비용과 마진콜 위험을 함께 알아야 해요.",
  },
  {
    id: "lv2-lev-5",
    level: "lv-2",
    topic: "대출 투자",
    topicIndex: 1,
    type: "MULTI",
    question: "다음 중 레버리지 사용을 특히 피해야 할 상황은 무엇일까?",
    options: [
      "생활비와 비상금이 충분하고 장기 계획이 분명한 경우",
      "시장 변동성이 낮고 포트폴리오가 잘 분산된 경우",
      "비상금이 부족하고 현금흐름이 불안정한 경우",
    ],
    answer: "비상금이 부족하고 현금흐름이 불안정한 경우",
    explanation: "상환 여력이 불안정하면 이자 부담과 손실이 겹쳐 위험이 커져요.",
  },
  {
    id: "lv2-lev-6",
    level: "lv-2",
    topic: "대출 투자",
    topicIndex: 1,
    type: "OX",
    question: "기초자산 가격이 제자리여도 이자와 수수료 때문에 레버리지 투자는 손실이 날 수 있다.",
    answer: "O",
    explanation: "레버리지는 이자·수수료가 꾸준히 발생해요. 자산이 오르지 않으면 비용만큼 수익이 깎여요.",
  },
];
