import { QuizItem } from "../types";

export const LV2_ECONOMIC_NEWS: QuizItem[] = [
  {
    id: "lv2-news-1",
    level: "lv-2",
    topic: "경제신문 활용법",
    topicIndex: 2,
    type: "OX",
    question: "경제신문은 시장 분위기 파악에는 도움이 되지만, 기업 뉴스는 얻기 어렵다.",
    answer: "X",
    explanation: "경제신문은 시장 분위기뿐 아니라 기업 뉴스까지 한눈에 알 수 있어요.",
  },
  {
    id: "lv2-news-2",
    level: "lv-2",
    topic: "경제신문 활용법",
    topicIndex: 2,
    type: "MULTI",
    question: "경제신문을 읽어야 하는 이유로 올바른 것은?",
    options: [
      "연예계 소식을 빠르게 알 수 있다",
      "시장 분위기를 빠르게 알 수 있다",
      "개인 일기처럼 사적인 경험을 공유한다",
    ],
    answer: "시장 분위기를 빠르게 알 수 있다",
    explanation: "경제신문은 시장 흐름과 기업 뉴스를 빠르게 파악하는 데 유용해요.",
  },
  {
    id: "lv2-news-3",
    level: "lv-2",
    topic: "경제신문 활용법",
    topicIndex: 2,
    type: "OX",
    question: "경제신문의 1면은 세부적인 기업 뉴스보다는 큰 흐름을 쉽게 알려준다.",
    answer: "O",
    explanation: "1면은 전체적인 경제 상황과 큰 이슈를 한눈에 보여줘요.",
  },
  {
    id: "lv2-news-4",
    level: "lv-2",
    topic: "경제신문 활용법",
    topicIndex: 2,
    type: "MULTI",
    question: "경제신문의 어떤 부분이 투자에 많은 도움이 되는가?",
    options: ["증권·산업 부분", "날씨 예보 부분", "스포츠 경기 부분"],
    answer: "증권·산업 부분",
    explanation: "증권·산업 부분은 투자 관련 정보가 풍부해서 큰 도움이 돼요.",
  },
  {
    id: "lv2-news-5",
    level: "lv-2",
    topic: "경제신문 활용법",
    topicIndex: 2,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["1면", "증권·산업면", "관심 있는 분야"],
    rightItems: ["큰 흐름을 쉽게 알려줌", "투자에 많은 도움 제공", "선택적으로 읽어도 됨"],
    answer: {
      "1면": "큰 흐름을 쉽게 알려줌",
      "증권·산업면": "투자에 많은 도움 제공",
      "관심 있는 분야": "선택적으로 읽어도 됨",
    },
    explanation: "경제신문은 구조에 따라 다르게 활용할 수 있어요.",
  },
  {
    id: "lv2-news-6",
    level: "lv-2",
    topic: "경제신문 활용법",
    topicIndex: 2,
    type: "OX",
    question: "경제신문을 읽을 때는 그래프와 숫자는 굳이 보지 않아도 된다.",
    answer: "X",
    explanation: "그래프와 숫자는 핵심 정보를 담고 있어서 꼭 체크해야 해요.",
  },
];
