import { QuizItem } from "../types";

export const LV2_ETF_INTRO: QuizItem[] = [
  {
    id: "lv2-etf-1",
    level: "lv-2",
    topic: "ETF",
    topicIndex: 3,
    type: "OX",
    question: "ETF는 주식처럼 거래소에서 사고팔 수 있는 펀드이다.",
    answer: "O",
    explanation: "ETF는 ‘상장지수펀드’로 거래소에 상장되어 주식처럼 쉽게 매매할 수 있어요.",
  },
  {
    id: "lv2-etf-2",
    level: "lv-2",
    topic: "ETF",
    topicIndex: 3,
    type: "MULTI",
    question: "ETF의 특징으로 옳지 않은 것은?",
    options: [
      "다양한 종목을 한 번에 담을 수 있다",
      "분산투자로 위험을 낮출 수 있다",
      "펀드라서 거래소에서는 매매할 수 없다",
    ],
    answer: "펀드라서 거래소에서는 매매할 수 없다",
    explanation: "ETF는 일반 펀드와 달리 거래소에서 자유롭게 매매할 수 있어요.",
  },
  {
    id: "lv2-etf-3",
    level: "lv-2",
    topic: "ETF",
    topicIndex: 3,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["ETF", "분산투자", "거래소"],
    rightItems: ["상장지수펀드", "다양한 종목에 나눠 투자하는 방법", "주식이나 ETF를 사고파는 시장"],
    answer: {
      ETF: "상장지수펀드",
      분산투자: "다양한 종목에 나눠 투자하는 방법",
      거래소: "주식이나 ETF를 사고파는 시장",
    },
    explanation: "ETF는 거래소에서 쉽게 사고팔 수 있는 분산투자형 펀드예요.",
  },
  {
    id: "lv2-etf-4",
    level: "lv-2",
    topic: "ETF",
    topicIndex: 3,
    type: "OX",
    question: "ETF는 소액으로도 분산투자가 가능하기 때문에 초보 투자자들에게 인기가 많다.",
    answer: "O",
    explanation: "ETF는 소액으로도 시장 전체에 분산투자할 수 있어 초보자들에게 매력적이에요.",
  },
  {
    id: "lv2-etf-5",
    level: "lv-2",
    topic: "ETF",
    topicIndex: 3,
    type: "MULTI",
    question: "다음 중 ETF의 장점이 아닌 것은?",
    options: [
      "일반 펀드보다 수수료가 저렴하다",
      "특정 지수를 추종한다",
      "개별 기업의 실적에만 투자한다",
    ],
    answer: "개별 기업의 실적에만 투자한다",
    explanation: "ETF는 특정 지수나 테마를 추종하는 상품으로, 개별 기업만을 겨냥하지 않아요.",
  },
  {
    id: "lv2-etf-6",
    level: "lv-2",
    topic: "ETF",
    topicIndex: 3,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["지수추종", "소액투자", "초보자 인기"],
    rightItems: [
      "특정 지수의 움직임을 그대로 따라가는 것",
      "적은 돈으로도 다양한 종목에 투자하는 것",
      "간편하고 쉬워서 투자 입문자에게 선호되는 것",
    ],
    answer: {
      지수추종: "특정 지수의 움직임을 그대로 따라가는 것",
      소액투자: "적은 돈으로도 다양한 종목에 투자하는 것",
      초보자: "간편하고 쉬워서 투자 입문자에게 선호되는 것",
    },
    explanation: "ETF는 지수를 추종하면서 소액으로 분산투자가 가능해 초보자들에게 인기가 많아요.",
  },
];
