import { QuizItem } from "../types";

export const LV2_EXCHANGE_RATE: QuizItem[] = [
  {
    id: "lv2-exrate-1",
    level: "lv-2",
    topic: "환율과 증시",
    topicIndex: 4,
    type: "OX",
    question: "환율은 국가 간 화폐의 교환 비율을 의미한다.",
    answer: "O",
    explanation: "환율은 한 나라의 화폐를 다른 나라 화폐로 바꾸는 비율을 말해요.",
  },
  {
    id: "lv2-exrate-2",
    level: "lv-2",
    topic: "환율과 증시",
    topicIndex: 4,
    type: "MULTI",
    question: "환율이 상승할 때 수출기업에 어떤 영향이 있을까?",
    options: ["수출 이익이 줄어든다", "수출 이익이 늘어난다", "큰 변화가 없다"],
    answer: "수출 이익이 늘어난다",
    explanation: "원화 가치가 하락하면 달러로 번 돈의 가치가 커져 수출기업 이익이 늘어나요.",
  },
  {
    id: "lv2-exrate-3",
    level: "lv-2",
    topic: "환율과 증시",
    topicIndex: 4,
    type: "MULTI",
    question: "환율이 상승해 원화 가치가 떨어질 때 내수기업에는 어떤 영향이 생길까?",
    options: ["수입 비용이 줄어든다", "원자재·부품 비용이 커진다", "실적이 개선된다"],
    answer: "원자재·부품 비용이 커진다",
    explanation: "환율이 오르면 원자재 수입 비용이 늘어나 내수기업 실적이 나빠질 수 있어요.",
  },
  {
    id: "lv2-exrate-4",
    level: "lv-2",
    topic: "환율과 증시",
    topicIndex: 4,
    type: "OX",
    question: "달러 가치가 오르면 항상 모든 주식이 오른다.",
    answer: "X",
    explanation: "달러 상승은 수출기업에는 유리하지만 내수기업에는 불리할 수 있어요.",
  },
  {
    id: "lv2-exrate-5",
    level: "lv-2",
    topic: "환율과 증시",
    topicIndex: 4,
    type: "COLOR",
    question: "단어와 뜻을 연결해보세요!",
    leftItems: ["환율", "수출기업", "내수기업"],
    rightItems: ["화폐의 교환 비율", "환율 상승 시 이익 증가", "환율 상승 시 비용 부담 증가"],
    answer: {
      환율: "화폐의 교환 비율",
      수출기업: "환율 상승 시 이익 증가",
      내수기업: "환율 상승 시 비용 부담 증가",
    },
    explanation: "환율과 기업의 관계를 한눈에 정리한 내용이에요.",
  },
  {
    id: "lv2-exrate-6",
    level: "lv-2",
    topic: "환율과 증시",
    topicIndex: 4,
    type: "MULTI",
    question: "투자자가 환율을 주의 깊게 봐야 하는 이유는?",
    options: [
      "기업 실적과 증시에 영향을 주기 때문",
      "환율은 개인 소비와만 관련 있기 때문",
      "주식과는 전혀 관련이 없기 때문",
    ],
    answer: "기업 실적과 증시에 영향을 주기 때문",
    explanation: "환율은 수출·내수기업의 실적에 직접적인 영향을 주기 때문에 투자자가 꼭 확인해야 해요.",
  },
];
